version: '2'
services:

  dedicated:
    image: johnjelinek/l4d2server
    hostname: l4d2
    container_name: l4d2
    ports   :
      - 27016:27015
      - 27016:27015/udp
    command: -game left4dead2 -strictportbind -ip 0.0.0.0 -port 27015 +clientport 27005 +map c5m1_waterfront -maxplayers 8
