FROM cod4lnx

# add configuration
ADD /configs/server.cfg /home/cod4/main/server.cfg

WORKDIR /home/cod4/

CMD ./cod4_lnxded +set dedicated 1 +sv_pure 1 +set fs_game mods/pml220 +exec server.cfg +map_rotate
