version: '2'
services:

  dedicated:
    image: rmoriz/openra
    hostname: openra
    ports   :
      - 1234:1234
    container_name: openra
    environment:
      - Name=OpenRA
      - Mod=ra
      - EnableSingleplayer=True
      - ListenPort=1234
      - ExternalPort=1234
      - Password=test
